# Topic 4

## kNN

> https://www.ibm.com/topics/machine-learning

> https://scikit-learn.org/stable/getting_started.html

***

Video 1 & 2


In [1]:
# imports

# numerical arrays
import numpy as np

# dataframes
import pandas as pd

# plotting
import matplotlib.pyplot as plt

# plotting
import seaborn as sns

# Machine Learning
import sklearn as sk


Scikit Notes:

"Each estimator can be fitted to some data using its fit method." -> scikit estimators / algorithms come with the same set of methods which you can call.

Fit  / train / estimate parameters -> Fit to algorithm - fit the data to the model

random_state=0  -> keep random numbers the same each time, so the same random numbers. better for testing - same random numbers for each time

Capital X - multidiamentional - input is a few numbers as opposed to one. Matrixes usually have capital letters. Variables have lower case. X is an array.

![Scipy](images/scipy_firstreview.jpg)

X  = [1,2,3] + [11,12,13]
y = [0,1]

Y here could be classes - so iris flowers? cars? etc the numbers relate to something as opposed to being a value.

clf.fit(X,y)
[1,2,3] of class [0]
[11,12,13] of class [1]

Clf.fit - fit the data to the classifier - classify the data / change for the training data and output the result.

This makes the data set very important.

This is a generic algorithm and the training data - with the fit method - maps the alorithm to new data and new outputs.

![Scipy](images/scipy_firstreview_fit.jpg)

The n_features in this case are the 11,12,13 or 1,2,3

3 samples 2 features in the above example

In unsupervised you may not have a y value - or not have a classifiying input

Regression - fit through line - best fit line 




In [2]:
# Interger Literals
i = 1

#show type
type(i)

int

In [3]:
# Float Literals
f = 1.0

#show type
type(f)


# i & f are not the same even though they look similiar and we may read them the same

float

In [4]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state=0)

X = [[ 1,  2,  3],  # 2 samples, 3 features
     [11, 12, 13]]

y = [0, 1]  # classes of each sample

clf.fit(X, y)

RandomForestClassifier(random_state=0)

In [5]:
clf.predict(X)

# repredict X
# so give it the inputs and see if the give outputs come out
# this will not work for all algorithms

array([0, 1])

In [6]:
clf.predict([[4, 5, 6], [14, 15, 16]])

# this is a new set of data
# the algorithm just works on numbers it doesnt care what they mean
# smaller set = 0 // 1,2,3 = 0
# larger set = 1 // 11,12,13 = 1

array([0, 1])

In [7]:
## things to consider

# what classifier should you use for your data set?

# is it too probabilisitic

# linear or non-linear?

# what parameters do you want to add to your classifier?

# preparing your dataset

# balance features - eg grams or kilograms? - are all data points weighted the same? for the algorithm is .5kg the same as 500g
# bring the data points down so better to use 500g as opposed to the .5kg 
# assume its normally distributed
# calculate the mean of the variable of the feature - down 
# subtract that from all the values - all values will still be in proportion
# then calculate the standard deviation of the feature - divide all numbers by that numbers
## ->> so you are bring the entire input data down



this completes the above

![Scipy](images/scipy_scaler.jpg)

In [8]:
# training set - approx 2/3 of the data set
# test - use approx 1/3 of the data set

# you can also leave a third to use as an evaluation part 

In [9]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn.model_selection.train_test_split

# For doing this training data set - shuffle the iris data fist
# you cannot just split it

Cross validataion
Splitting the data to use as trainging/ testing / evaluating

![image.png](images/scipy_crossvalidate.jpg)


This page on Scikit learn is a good first step to review before you start 

Knowing what to use and how is where the difficulty lies:

Scalling features / choosing an algorithm / organising the algorithm 



***
***

# code

Video 3

> https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

> https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv

***

In [10]:
# Load penguins data set

df = pd.read_csv('files/penguins.csv')

# show
df


# you could also take the file from https://github.com/mwaskom/seaborn
# as we can see if that this dataset has missing values

# some algorithms will deal with the missing values
# some algorithms will ignore the data and move on
# some algorithms will intiuite what it could be / or use the rest of the data on the row

# we need to look at data and make a decision prior to running
# changing a parameter may also help

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [11]:
# imported Sklearn as Sk so can call this slightly differently that from the documentation

# create a new instance of the classifier
# the code is a "plan"  but we need to feed into it to get it to work
# () call the class
clf = sk.neighbors.KNeighborsClassifier()

In [12]:
# The X Values

# the brackets on the outside are for getting the values in the array
# the brackets on the inside just mean list
X = df[['bill_length_mm','bill_depth_mm','flipper_length_mm', 'body_mass_g']]

X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
3               NaN            NaN                NaN          NaN
4              36.7           19.3              193.0       3450.0
..              ...            ...                ...          ...
339             NaN            NaN                NaN          NaN
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[344 rows x 4 columns]

In [13]:
# X is a data frame
type(X)

pandas.core.frame.DataFrame

In [14]:
# X to numpy array
X.to_numpy()

array([[  39.1,   18.7,  181. , 3750. ],
       [  39.5,   17.4,  186. , 3800. ],
       [  40.3,   18. ,  195. , 3250. ],
       ...,
       [  50.4,   15.7,  222. , 5750. ],
       [  45.2,   14.8,  212. , 5200. ],
       [  49.9,   16.1,  213. , 5400. ]])

In [15]:
# y values

y = df['sex']

y

0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...  
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: object

In [16]:
# fit the data (((((Un-hashout this and run when testing)))))

#clf.fit(X , y)

# you will get an error because there are null values
# note in the error there is an allow nan option

***

Video 4

> https://en.wikipedia.org/wiki/NaN 


NaN is something you cannot calculate / not a number

None is No Value

NaN comes from the Math Package

<br/>

Explaination:

> https://pandas.pydata.org/docs/user_guide/missing_data.html

NaN allows pandas to continue to operate quickly as its already built in from Math


![Nan](images/NaN.jpg)

In [17]:
# look for NaNa

# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html

df.isna()

# falses where there are values

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      False   False           False          False              False   
1      False   False           False          False              False   
2      False   False           False          False              False   
3      False   False            True           True               True   
4      False   False           False          False              False   
..       ...     ...             ...            ...                ...   
339    False   False            True           True               True   
340    False   False           False          False              False   
341    False   False           False          False              False   
342    False   False           False          False              False   
343    False   False           False          False              False   

     body_mass_g    sex  
0          False  False  
1          False  False  
2          False  False  
3           True   True  
4          False  False  
..           ...    ...  
339         True   True  
340        False  False  
341        False  False  
342        False  False  
343        False  False  

[344 rows x 7 columns]

In [18]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

df_nona = df.dropna()

df_nona

# 344 rows to 333

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
4         3450.0  FEMALE  
5         3650.0    MALE  
..           ...     ...  
338       4925.0  FEMALE  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[333 rows x 7 columns]

Best practice is to complete this prior to splitting the datas set into X and y

*always review the dataset first - looking fo NaN values and other irregularities


In [20]:
X = df_nona[['bill_length_mm','bill_depth_mm','flipper_length_mm', 'body_mass_g']]

X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
4              36.7           19.3              193.0       3450.0
5              39.3           20.6              190.0       3650.0
..              ...            ...                ...          ...
338            47.2           13.7              214.0       4925.0
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[333 rows x 4 columns]

In [21]:
y = df_nona['sex']

y

0        MALE
1      FEMALE
2      FEMALE
4      FEMALE
5        MALE
        ...  
338    FEMALE
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 333, dtype: object

In [23]:
# reclassify
clf = sk.neighbors.KNeighborsClassifier()

In [24]:
# re-fit the data

clf.fit(X , y)


KNeighborsClassifier()

In [25]:
df_nona.iloc[0]

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       MALE
Name: 0, dtype: object

In [26]:
X.iloc[0]

bill_length_mm         39.1
bill_depth_mm          18.7
flipper_length_mm     181.0
body_mass_g          3750.0
Name: 0, dtype: float64

In [ ]:
#clf.predict(X.iloc[0])

# this will output an error also - it wants a 2D array

In [27]:
clf.predict([X.iloc[0]])

# will still get a warning

c:\Users\V\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['MALE'], dtype=object)

In [29]:
# Correct format is as follows

# this is a correct check that the classifier correctly predicts first sample
clf.predict(X.iloc[:1])

# first element if the X array
# :1 - up to but not including 1 therefore [0]

array(['MALE'], dtype=object)

What we have done so far is build the classifier

We have inputted 4 values ( bill length, bill_depth, flipper_length, body_mass_g) and used these to predict sex

<br/>

What did we do:

Loaded Dataset

If there were NaNs delete row

Selected variables for input (4 Columns = X)

Selected Output Values ( 1 Column =y)

Trained the classifer with all values - Fit Method

Then we checked the first value 

Then we predicted it - it matched - Male

<br/>

Now this could tell the sex of a penguin based on these measurements


<br/>

Difficulties:

Getting data in correct format

Missing data

What are inputs?

What are outputs?

What classifier?

Do the parameters need to be changed?


<br/>

None of these are programming issues --> the theory is the hard part. This is the difficulty with machine learning.


***

Video 5

Note there is a mistake in the Minkowski distance (p missing from formula):

> https://www.ibm.com/topics/knn