# Task Sheets

Biweekly Task Sheet Submissions - Machine Learning and Statistics - Winter 2023 / 2024

Lecturer Ian McLoughlin

Task Sheet PDFs included in Supporting Data Folder

***


add in links to each task sheet

***

<br/>

<h2><center> Task Sheet 1 </center></h2>

    

### Question 1

Newtons Method

> Write a function $ sqrt (x) $ to approximate the square root of a floating point number $ x $ without using the power operator or a package.

> Rather you should use Newton's method. Start with an initial guess for the square root called $ z_{0} $. You then repeatly improve it using the folowing formula, until the difference between a previous guess $ z_{i} $ and the next $ z_{i + 1} $ is less than some threshold for example 0.01.


$$
  z_{i + 1}  =  z_{i} - \frac{ \ z_{i}  *  z_{i} - x }{ 2z_{i} }
$$


<br/>


T1 Q1 Links:

[Go Programming language](https://go.dev/tour/welcome/1)

[Loops and Functions in Go](https://go.dev/tour/flowcontrol/8)

[Newton Sq Rt](https://math.mit.edu/~stevenj/18.335/newton-sqrt.pdf)


[1][2][3][4][5]

To test our function we will use test data - we will use data where we know the outcome and test that the program finds this answer.

A Square root of a number is a value that when multipled by itself will give the original number. [6]

Newtons Function asks us to start with a guess point and when the function is run repeatedly we get the result. As outlined in UT Calculus; "In typical situations, Newton's method homes in on the answer extremely quickly, roughly doubling the number of decimal points in each round. So if your original guess is good to one decimal place, 5 rounds later you will have an answer good to 30+ digits." [7]

Test Variables: To test the function we will look for the square root of 16, which we know to be 4. As as starting point we will guess 2 to be the correct answer. Using these variables / parameters we will run the function.

Once we have confirmed that our function is working correctly and we have tested it we can then change variables and use it to calculate the square root of other numbers.

In [2]:
# Alternative Options to Newtons Method:

# python will allow you to work out the Square Root as following -

16 ** 0.5


# in this instance we are raising 16 to the power of 0.5 

# [8]

4.0

In [3]:
# Using Python Packages this can also be achieve by the following:
import math

# square root of the number 16
math.sqrt(16) 

# for this page you cannot use a negative number - these will always be positive numbers
# however for this Question we are using Newtons Method as opposed to power operators or packages.

# [9]

4.0

We will now plot the Equation - inputting our variables

In [4]:
# Set x  - the number we want to calculate the square root of

x = 16

In [5]:
# Set z - this number is our initial guess or starting point for what we think the square root could be

z = 2.0

# note we are setting this as a floating number
# unless the Square root is a full number, or perfect square, outcomes will be a floating point

In [6]:
# First Appoximation


znext = z - (((z * z) - x) / ( 2*z )) 

# setting a variable called znext - or our next guess
# using Newtons formula above write a formula in Python
# note 2z is written as 2*z in Python
# precendence operators - ensures that multiplication before subtraction

# znext equals, z minus the results of z multiplied by z minus x, divided by 2z (z * 2)

znext

# print znext

5.0

Evaluation of first run:

Is 5.0 a better approximation?

Yes, 2 is 2 units away from 4, where as 5 is 1 unit away.

Continuing to run this formula and you will get you closer to the required number 4. This shows the repeating nature of this formula and its importance in Machine Learning - this formula will more accurate with each time it is run further writing full functions will allow for us to set it to run with a error margain and also a maximum number of iterations.

In [7]:
# Write a formula to complete this process in one instance
# the following is a version of Newton's method where we set the number of times where the funcion will run - 100 times

def sqrt(x):
    # initial guess for the sq rt
    z = x / 4.0
    # iteration is used in this function - this function is run 100 times - this can be set as a variable and run any number of times
    for i in range(100):
        # Newton's method for a better approximation.
        z - (((z * z) - x) / ( 2*z )) 


    return z


In [8]:
# run the above function

sqrt(16)

4.0

In the above method we are using iteraiton and setting the number of times the function will run, in this instance we have set this for 100. What if we have a  number where to get the correct value we need to run the function 101 times?

There for a while loop which would complete evaluations and continue to run while conditions are being met is a better version.

In [14]:
# here we use a while loop to continue to fun the formula while conditions are being met
# We use both an approximate as a starting point and then incoropating the better guess from each time the code is run

def while_sqrt(n):
    approx=0.5*n
    better=0.5*(approx+n/approx)
    while better!=approx:
        approx=better
        better=0.5*(approx+n/approx)
    return approx



# [10]

In [15]:
# run the above function on our test number 16

while_sqrt(16)

4.0

In [16]:
while_sqrt(2)

1.414213562373095

<img src="C:\Users\V\Repo\MachineLearning_Statistics\Supporting Data\Images" alt="Alternative text" />

Notes / observations from Question 1:




1. the method is not efficient to calculate the roots of the polynomials or equations with higher degrees but in the case of small-degree equations, this method yields very quick results. I
https://www.geeksforgeeks.org/newton-raphson-method/

2. deivatives instandeous rate of change - change in x approaches 0 - iterate through formula to get 0 - 

<br/>



### Question 2

Chi-squared

> Consider a contingency table, based on a survey asking preferences between coffee or tea, and plain & chocolate biscuits.

> Use scipy.stats to perform a chi-squared test to see whether there is any evidence of an assocciation between drink preference and biscuit preference.


              

|             | *biscuits* Chocolate  | Plain   |
| -:| -: | -: |
| *Drink* Coffee|        43  |      57 |
|       Tea   |        56  |      45 |


<br/>



<br/>


T1 Q2 Links:



In [11]:
import numpy as np
from scipy.stats import chi2_contingency


table = np.array([[90, 60, 104, 95],
                  [30, 50,  51, 20],
                  [30, 40,  45, 35]])

chi2, p, dof, expected = chi2_contingency(table)

print(f"chi2 statistic:     {chi2:.5g}")
print(f"p-value:            {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic:     24.571
p-value:            0.00040984
degrees of freedom: 6
expected frequencies:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


In [12]:
import numpy as np
from scipy.stats import chi2_contingency


table = np.array([[43, 57],
                  [56, 45]])

chi2, p, dof, expected = chi2_contingency(table)

print(f"chi2 statistic:     {chi2:.5g}")
print(f"p-value:            {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic:     2.6359
p-value:            0.10447
degrees of freedom: 1
expected frequencies:
[[49.25373134 50.74626866]
 [49.74626866 51.25373134]]


# Bibliography

[]

[] Linuxhint, How to use latex in Jupyter Notebook, 2021, https://linuxhint.com/use-latex-jupyter-notebook/

[] Patrick Walls Github, 2022 https://patrickwalls.github.io/mathematicalpython/jupyter/latex/ & https://github.com/patrickwalls/mathematicalpython/blob/master/notebooks/jupyter/latex.ipynb


## Task 1 Newtons Method

[1] StackOverflow, Centering Text in IPython notebook markdown/heading cells?, 2013 https://stackoverflow.com/questions/18575012/centering-text-in-ipython-notebook-markdown-heading-cells

[2] Maths and Equations, Jupyterbook.org, 2022, https://jupyterbook.org/en/stable/content/math.html

[3] MyST Markedly Structured Text, Sept 20 2023, https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-amsmath 

[4] Real Python, The Python Square Root Function, July 08 2019, https://realpython.com/python-square-root-function/

[5] Splash Learn, What Are Square and Square Roots?, https://www.splashlearn.com/math-vocabulary/algebra/square-and-square-roots#:~:text=The%20square%20root%20of%20a,themselves%2C%20give%20the%20product%2025.

[] UT Calcalas, Department of Mathematices at UT Austin, https://web.ma.utexas.edu/users/m408n/CurrentWeb/LM4-8-2.php#:~:text=Newton's%20method%20is%20a%20technique,a%20new%20(and%20improved!)

[] Enterprise DNA Blog, Python ** Explained (Double Star or Double Asterix),  https://blog.enterprisedna.co/what-does-double-star-mean-in-python/#:~:text=The%20double%20star%20operator%2C%20denoted,calls%20to%20unpack%20keyword%20arguments.

[] Medium.com, Python program to find square root of the number using Newton’s method, 2021 https://thirumalai2024.medium.com/python-program-to-find-square-root-of-the-number-using-newtons-method-937c0e732756

[1] Newtons Method in Python, Studysession, 2021, https://www.youtube.com/watch?v=99ABkygm2Xg

[]

[]